name: Run Terraform Validate

on: [push]

jobs:
  Deploy:
    name: Validate the Terraform files
    runs-on: ubuntu-22.04
    container: hashicorp/terraform:0.14.9
    steps:
    - uses: actions/checkout@v2
    - name: Initialize the terraform modules
      run: terraform init
    - name: Validate the terraform files
      run: terraform validate